// Detailed prompt descriptions for each exterior design style
// These descriptions help the AI generate more accurate style-specific exterior imagery

export const EXTERIOR_STYLE_PROMPTS: Record<string, string> = {
	modern: `sleek contemporary architecture with clean geometric lines, 
		flat or low-pitched roofs, large windows with minimal frames, 
		neutral color palette with white, grey, black, or earth tones, 
		smooth exterior materials like stucco, metal panels, or fiber cement, 
		straight-edged design elements, minimal ornamental details, 
		contemporary materials like glass and steel, 
		simple geometric shapes and volumes, 
		uncluttered facade design, emphasis on horizontal lines, 
		modern architectural details like cantilevers or overhangs, 
		landscaped entry with contemporary design elements`,

	bohemian: `eclectic and artistic exterior design with diverse architectural elements, 
		warm earthy tones with pops of vibrant colors in trim or accents, 
		mixed materials creating texture and visual interest, 
		unique architectural details and decorative elements, 
		porches or verandas with eclectic styling, 
		ornamental details and artistic touches, 
		natural materials like wood, stone, or handcrafted tiles, 
		informal and lived-in appearance, 
		global-inspired architectural influences, 
		plants and greenery integrated into design, 
		creative use of color and pattern in exterior finishes`,

	'dark-academia': `formal architectural style with classical influences, 
		dark exterior colors including deep grays, dark browns, or burgundy, 
		ornamental architectural details like columns, cornices, or pediments, 
		traditional materials like brick, stone, or dark wood siding, 
		formal window arrangements with divided lights, 
		stone or brick accents, 
		scholarly and intellectual architectural aesthetic, 
		classical proportions and symmetry, 
		aged and weathered appearance suggesting history and tradition, 
		formal landscaping with structured plantings, 
		architectural elements suggesting classical education and heritage`,

	'dark-behemian': `moody exterior design with dark color palette, 
		deep purples, blacks, dark greens, or dark grays in exterior finishes, 
		eclectic architectural elements with gothic or mysterious influences, 
		textured exterior materials creating depth and shadow, 
		dramatic architectural details and ornate features, 
		unconventional and artistic exterior design, 
		mysterious and enchanting building appearance, 
		dark materials like slate, dark brick, or charcoal siding, 
		atmospheric and moody exterior lighting considerations, 
		artistic architectural details blending styles creatively`,

	scandinavian: `light and airy exterior design with simplicity and functionality, 
		light color palette featuring whites, pale grays, or light wood tones, 
		clean architectural lines, 
		natural materials like light wood siding or painted wood, 
		simple geometric forms and minimalist design, 
		large windows for natural light, 
		understated architectural details, 
		functional and practical exterior design, 
		cozy and welcoming appearance, 
		natural landscaping complementing the light aesthetic, 
		emphasis on quality materials and craftsmanship`,

	industrial: `urban industrial exterior with raw materials and utilitarian design, 
		exposed materials like corrugated metal, concrete, or brick, 
		metal architectural elements and steel accents, 
		contemporary industrial aesthetic, 
		utilitarian design with function over decoration, 
		neutral color palette with grays and browns, 
		modern industrial materials and finishes, 
		straightforward architectural form, 
		warehouse or loft-style building appearance, 
		industrial windows and architectural glazing, 
		urban and contemporary exterior design`,

	traditional: `classic architectural style with timeless design elements, 
		formal and symmetrical facade design, 
		traditional materials like brick, stone, or wood siding, 
		classical architectural details like columns, shutters, or decorative trim, 
		warm color palette with traditional exterior colors, 
		pitched roofs with gables or dormers, 
		traditional window styles with divided lights or shutters, 
		formal entry with classical architectural elements, 
		timeless and elegant exterior appearance, 
		balanced proportions and traditional architectural proportions, 
		welcoming and established residential aesthetic`,

	minimalist: `ultra-clean exterior design with extreme simplicity, 
		monochromatic color scheme, 
		simple geometric forms, 
		uncluttered facade with minimal decorative elements, 
		clean lines and streamlined design, 
		contemporary materials with smooth finishes, 
		emphasis on form and function, 
		calm and serene exterior appearance, 
		focus on essential architectural elements only, 
		modern minimalist aesthetic, 
		reduction of visual complexity to core architectural elements`,

	rustic: `natural materials and warm earthy aesthetic, 
		wood siding, stone, or natural materials prominently featured, 
		warm earth tones and natural wood finishes, 
		craftsman-style architectural details, 
		handcrafted architectural elements, 
		organic and natural appearance, 
		textured exterior materials creating warmth, 
		country or cottage architectural influences, 
		traditional construction methods visible, 
		weathered or aged material appearances, 
		cozy and welcoming residential exterior`,

	contemporary: `current architectural trends with fresh design approaches, 
		mix of traditional and modern exterior elements, 
		innovative use of materials and architectural forms, 
		current exterior design trends, 
		modern architectural details with contemporary sensibility, 
		flexible design approach blending styles, 
		up-to-date exterior finishes and materials, 
		fresh and current architectural appearance, 
		contemporary color palette and material choices, 
		modern lifestyle considerations in design, 
		innovative architectural solutions`,

	tropical: `lush and vibrant exterior with tropical architectural influences, 
		bright colors and tropical-inspired design elements, 
		open architectural elements like verandas or wide porches, 
		lush landscaping integrated with architecture, 
		tropical materials like bamboo or palm thatch accents, 
		bright and welcoming exterior appearance, 
		relaxed tropical aesthetic, 
		tropical color combinations, 
		outdoor living areas integrated into design, 
		nature-inspired architectural details, 
		vacation or resort-style architectural influences`,

	'art-deco': `geometric patterns and streamlined architectural design, 
		Art Deco geometric motifs in exterior details, 
		smooth exterior surfaces with decorative geometric elements, 
		bold horizontal lines and zigzag patterns, 
		streamlined and sophisticated architectural style, 
		1920s-1930s architectural influences, 
		geometric window arrangements and decorative details, 
		stylized architectural ornamentation, 
		geometric decorative elements integrated into facade, 
		glamorous and sophisticated exterior appearance, 
		distinctive Art Deco architectural character`,

	'modern-farmhouse': `combination of modern and farmhouse architectural styles, 
		traditional farmhouse elements with contemporary updates, 
		white or light-colored exterior with black accents, 
		board and batten or traditional siding materials, 
		modern farmhouse architectural details, 
		welcoming and comfortable exterior appearance, 
		traditional gabled roofs with modern proportions, 
		large front porches or verandas, 
		country aesthetic with contemporary touches, 
		rustic charm with modern amenities visible, 
		warm and inviting residential character`,

	coastal: `light and airy exterior with coastal architectural influences, 
		light color palette with blues, whites, and sandy tones, 
		beach or coastal architectural style, 
		relaxed and breezy exterior appearance, 
		weather-resistant materials suitable for coastal environments, 
		open architectural elements like porches or decks, 
		coastal color combinations, 
		relaxed beach aesthetic, 
		natural landscaping with coastal plants, 
		vacation home or beach house architectural character, 
		welcoming and relaxing exterior design`,

	japandi: `minimalist design blending Japanese and Scandinavian influences, 
		clean lines with natural materials, 
		natural wood tones and minimalist color palette, 
		simple geometric forms with attention to detail, 
		calm and serene exterior appearance, 
		Japanese architectural influences with Scandinavian simplicity, 
		quality materials with understated elegance, 
		natural landscaping complementing architectural style, 
		balance between simplicity and warmth, 
		contemporary design with traditional influences, 
		tranquil and harmonious exterior aesthetic`,

	'french-country': `rustic French architectural style with country charm, 
		stone or stucco exterior with wood accents, 
		traditional French country architectural details, 
		warm earth tones and natural materials, 
		shuttered windows and French country elements, 
		charming and rustic exterior appearance, 
		traditional French architectural proportions, 
		naturally aged or weathered material appearance, 
		country estate architectural character, 
		welcoming provincial aesthetic, 
		classic French country architectural details`,

	'shabby-chic': `vintage and distressed exterior with romantic charm, 
		weathered or aged exterior finishes, 
		soft color palette with pastels or muted tones, 
		vintage architectural elements and decorative details, 
		romantic and charming exterior appearance, 
		distressed materials creating character, 
		traditional cottage architectural influences, 
		ornamental decorative elements, 
		feminine and romantic exterior aesthetic, 
		vintage styling with comfortable charm, 
		lived-in and cherished building appearance`,

	transitional: `blend of traditional and contemporary exterior design, 
		balanced approach combining classic and modern elements, 
		transitional color palette, 
		timeless architectural details with contemporary updates, 
		versatile exterior design appealing to broad tastes, 
		classic proportions with modern materials, 
		sophisticated and balanced architectural approach, 
		traditional architectural foundation with contemporary refinements, 
		enduring design with modern sensibility, 
		refined and polished exterior appearance, 
		elegant transition between traditional and contemporary styles`,
};

/**
 * Get the detailed prompt for a specific exterior style
 */
export function getExteriorStylePrompt(styleId: string): string {
	// Normalize the style ID (lowercase, replace spaces with hyphens)
	const normalizedId = styleId.toLowerCase().replace(/\s+/g, '-');
	return EXTERIOR_STYLE_PROMPTS[normalizedId] || '';
}

/**
 * Check if an exterior style has a detailed prompt
 */
export function hasExteriorStylePrompt(styleId: string): boolean {
	const normalizedId = styleId.toLowerCase().replace(/\s+/g, '-');
	return Object.prototype.hasOwnProperty.call(EXTERIOR_STYLE_PROMPTS, normalizedId);
}
