// Detailed prompt descriptions for each floor type
// These descriptions help the AI generate more accurate floor-specific imagery

export const FLOOR_STYLE_PROMPTS: Record<string, string> = {
	'oak-hardwood': `beautiful natural oak hardwood flooring with warm honey brown tones, 
		visible wood grain patterns showing natural character, 
		medium width planks with subtle variation in color, 
		semi-gloss or satin finish reflecting light naturally, 
		classic hardwood texture with natural knots and grain variation, 
		warm and inviting appearance, 
		traditional wood flooring aesthetic with timeless appeal, 
		natural wood texture showing authentic grain patterns, 
		professional hardwood installation with tight seams`,

	'walnut-hardwood': `rich dark walnut hardwood flooring with deep chocolate brown tones, 
		dramatic wood grain patterns with natural color variation, 
		luxurious appearance with deep saturated color, 
		wide plank installation showing premium quality, 
		sophisticated dark wood aesthetic, 
		satin or matte finish for refined look, 
		natural wood texture with visible grain character, 
		high-end hardwood flooring with elegant appearance, 
		warm undertones in the dark wood creating inviting space`,

	'light-oak': `light natural oak wood flooring with pale blonde tones, 
		subtle grain patterns creating airy spacious feel, 
		scandinavian-inspired light wood aesthetic, 
		wide planks with minimal color variation, 
		natural matte or satin finish, 
		contemporary light wood look, 
		fresh and bright appearance, 
		subtle texture showing wood grain, 
		modern nordic flooring style`,

	'white-marble': `luxurious white marble flooring with elegant grey veining, 
		polished surface with high-gloss reflective finish, 
		natural stone patterns with subtle grey and cream veining, 
		large format marble tiles with thin grout lines, 
		sophisticated classical marble aesthetic, 
		cool white tones with warm undertones, 
		premium natural stone appearance, 
		elegant and timeless marble texture, 
		high-end stone flooring installation`,

	'black-marble': `dramatic black marble flooring with white and gold veining, 
		polished glossy surface reflecting light beautifully, 
		bold sophisticated dark stone aesthetic, 
		luxurious appearance with natural stone patterns, 
		large marble tiles with elegant veining detail, 
		high-contrast dramatic flooring, 
		premium dark stone with metallic vein accents, 
		glamorous art-deco inspired marble look, 
		sophisticated luxury stone flooring`,

	'grey-marble': `contemporary grey marble flooring with subtle white veining, 
		modern stone aesthetic with cool neutral tones, 
		polished or honed marble finish, 
		elegant grey stone with natural variation, 
		large format tiles with minimal grout lines, 
		sophisticated contemporary marble look, 
		natural stone texture with flowing vein patterns, 
		versatile neutral stone flooring, 
		modern luxury marble installation`,

	'ceramic-tile': `classic ceramic tile flooring with uniform appearance, 
		clean grout lines creating geometric grid pattern, 
		durable practical tile surface, 
		smooth ceramic finish with subtle sheen, 
		consistent color and texture across tiles, 
		traditional tile installation with neat alignment, 
		practical and attractive ceramic flooring, 
		medium size tiles with proportional grout spacing, 
		timeless tile aesthetic`,

	'porcelain-tile': `premium porcelain tile flooring with refined appearance, 
		large format tiles with minimal grout lines, 
		sophisticated uniform surface, 
		contemporary tile installation, 
		subtle texture or polished finish, 
		high-quality porcelain with clean lines, 
		modern tile aesthetic with seamless look, 
		durable luxury tile flooring, 
		professional installation with precise alignment`,

	'travertine': `warm travertine stone flooring with natural pitted texture, 
		beige and cream earth tones with natural variation, 
		rustic elegance with authentic stone character, 
		tumbled or honed finish showing natural texture, 
		mediterranean-inspired stone aesthetic, 
		organic patterns and color variation, 
		natural stone with characteristic surface texture, 
		warm inviting stone flooring, 
		classic travertine with natural beauty`,

	'slate': `natural slate stone flooring with rich textured surface, 
		deep grey and charcoal tones with subtle color variation, 
		distinctive cleft surface showing natural layers, 
		rustic contemporary stone aesthetic, 
		organic irregular patterns, 
		matte finish with natural stone texture, 
		architectural stone with character, 
		durable natural slate installation, 
		earthy sophisticated stone flooring`,

	'limestone': `elegant limestone flooring with soft neutral tones, 
		beige and cream colors with subtle natural variation, 
		smooth honed finish or slightly textured surface, 
		classical natural stone aesthetic, 
		consistent appearance with gentle color shifts, 
		timeless stone flooring with refined look, 
		warm neutral stone with sophisticated appeal, 
		natural limestone with elegant character, 
		classic stone installation`,

	'concrete-polished': `modern polished concrete flooring with smooth industrial finish, 
		contemporary grey surface with subtle sheen, 
		minimalist aesthetic with clean appearance, 
		industrial-chic concrete look, 
		smooth troweled surface with slight reflection, 
		urban modern flooring style, 
		architectural concrete with refined finish, 
		contemporary grey tones with subtle variation, 
		seamless concrete floor installation`,

	'concrete-textured': `textured concrete flooring with contemporary industrial character, 
		brushed or stamped surface pattern, 
		modern urban aesthetic with architectural appeal, 
		grey concrete with intentional texture, 
		industrial design with refined execution, 
		contemporary textured surface, 
		architectural concrete with visual interest, 
		modern industrial flooring style, 
		sophisticated concrete with tactile quality`,

	'terrazzo': `classic terrazzo flooring with colorful stone chips in concrete, 
		polished smooth surface with glossy finish, 
		mid-century modern aesthetic with playful pattern, 
		multicolored aggregate creating speckled appearance, 
		retro-contemporary terrazzo style, 
		smooth polished composite surface, 
		artistic stone chip pattern throughout, 
		vintage-inspired modern flooring, 
		sophisticated terrazzo with colorful detail`,

	'herringbone-wood': `elegant herringbone pattern hardwood flooring, 
		classic diagonal zigzag wood plank arrangement, 
		sophisticated parquet-style wood installation, 
		warm natural wood tones in geometric pattern, 
		traditional european wood flooring design, 
		medium brown wood with visible grain, 
		timeless herringbone layout with precision joints, 
		architectural wood flooring pattern, 
		refined classic wood installation`,

	'chevron-wood': `sophisticated chevron pattern hardwood flooring, 
		v-shaped zigzag wood plank arrangement with point joints, 
		premium parquet-style wood installation, 
		elegant geometric wood pattern, 
		french-inspired wood flooring design, 
		seamless angled joints creating continuous pattern, 
		luxury wood flooring with architectural appeal, 
		precise chevron layout with perfect alignment, 
		high-end decorative wood installation`,

	'bamboo': `sustainable bamboo flooring with natural honey tones, 
		distinctive bamboo grain with linear patterns, 
		eco-friendly wood alternative with warm appearance, 
		contemporary sustainable flooring aesthetic, 
		natural bamboo texture with subtle variation, 
		modern environmentally-conscious floor, 
		smooth bamboo surface with natural character, 
		warm golden-brown bamboo tones, 
		contemporary green building flooring`,

	'cork': `natural cork flooring with warm honey brown color, 
		distinctive cork texture with natural variation, 
		sustainable comfortable flooring surface, 
		soft appearance with organic texture, 
		eco-friendly natural cork aesthetic, 
		warm neutral tones with subtle pattern, 
		contemporary sustainable floor covering, 
		natural cork with inviting character, 
		modern green building material`,

	'luxury-vinyl-wood': `premium luxury vinyl plank flooring mimicking wood, 
		realistic wood grain texture and appearance, 
		contemporary wood-look vinyl installation, 
		practical durable flooring with wood aesthetic, 
		modern vinyl plank with authentic wood pattern, 
		wide planks with realistic grain detail, 
		waterproof wood-look flooring, 
		convincing wood texture reproduction, 
		contemporary practical wood-alternative floor`,

	'luxury-vinyl-tile': `high-end luxury vinyl tile with stone appearance, 
		realistic stone or tile texture pattern, 
		contemporary vinyl tile installation, 
		practical luxury tile alternative, 
		authentic tile look with vinyl durability, 
		modern waterproof tile-look flooring, 
		sophisticated vinyl with stone aesthetic, 
		realistic texture and appearance, 
		contemporary practical floor covering`,

	'painted-wood': `painted wood flooring in crisp white or custom color, 
		smooth painted surface over wood planks, 
		cottage or farmhouse style painted floor, 
		matte or semi-gloss painted finish, 
		charming rustic-modern painted wood aesthetic, 
		clean uniform color over wood texture, 
		architectural painted wood floor, 
		contemporary painted plank flooring, 
		casual refined painted wood surface`,

	'reclaimed-wood': `characterful reclaimed wood flooring with rustic appeal, 
		varied weathered wood with authentic aged patina, 
		mixed width planks with natural imperfections, 
		sustainable salvaged wood with history, 
		rustic contemporary aesthetic with texture, 
		natural aged wood with character marks, 
		authentic vintage wood appearance, 
		warm rustic tones with variation, 
		architectural salvaged wood installation`,

	'wide-plank-oak': `premium wide plank oak hardwood flooring, 
		generous plank width showing natural wood beauty, 
		contemporary rustic wood aesthetic, 
		natural oak grain highlighted by wide format, 
		modern farmhouse wood flooring style, 
		warm natural oak tones with minimal finish, 
		architectural wide plank installation, 
		sophisticated casual wood floor, 
		contemporary wood with traditional appeal`,

	'grey-wash-wood': `modern grey-washed wood flooring with cool tones, 
		contemporary wood finish with grey undertones, 
		scandinavian-inspired grey wood aesthetic, 
		subtle wood grain visible through grey wash, 
		modern neutral wood flooring, 
		cool grey-brown wood tones, 
		contemporary weathered wood look, 
		architectural grey wood floor, 
		modern nordic wood finish`,

	'natural-stone-blend': `mixed natural stone flooring with varied earth tones, 
		multi-color stone with beige, brown, and grey tones, 
		rustic natural stone pattern with variation, 
		tumbled or honed mixed stone finish, 
		organic stone aesthetic with natural diversity, 
		mediterranean-inspired mixed stone floor, 
		warm earth-tone stone with character, 
		natural stone mosaic appearance, 
		architectural mixed stone installation`,

	'white-oak': `beautiful white oak hardwood flooring with light neutral tones, 
		pale natural wood with subtle grey undertones, 
		contemporary light wood aesthetic, 
		wide planks showing white oak grain patterns, 
		modern neutral wood flooring, 
		natural matte or satin finish, 
		sophisticated light hardwood look, 
		clean contemporary wood floor, 
		architectural white oak installation`,

	'dark-walnut': `luxurious dark walnut hardwood with rich espresso tones, 
		deep brown nearly black wood with dramatic grain, 
		sophisticated dark hardwood aesthetic, 
		premium dark wood flooring, 
		elegant wide plank dark wood installation, 
		contemporary luxury wood floor, 
		dramatic dark brown wood with character, 
		high-end dark hardwood with refinement, 
		architectural dark wood installation`,

	'geometric-tile': `contemporary geometric tile pattern flooring, 
		modern tile layout with hexagonal or diamond shapes, 
		architectural tile design with visual interest, 
		clean geometric pattern with precise alignment, 
		contemporary decorative tile installation, 
		monochromatic or two-tone geometric design, 
		modern artistic tile floor, 
		sophisticated geometric tile pattern, 
		architectural decorative tile work`,

	'encaustic-tile': `colorful encaustic cement tile with pattern, 
		traditional decorative tile with bold design, 
		mediterranean or spanish-inspired tile pattern, 
		vibrant colors in geometric or floral motifs, 
		artisanal decorative tile aesthetic, 
		handcrafted appearance with pattern detail, 
		colorful traditional tile installation, 
		artistic patterned cement tile floor, 
		bold decorative tile with character`,

	'brick-flooring': `warm brick flooring with rustic industrial charm, 
		traditional brick pattern with natural clay tones, 
		textured brick surface with authentic character, 
		industrial or farmhouse brick aesthetic, 
		red-orange brick with natural variation, 
		rustic contemporary brick floor installation, 
		traditional masonry flooring, 
		architectural brick with weathered appeal, 
		authentic clay brick flooring`,
};

// Floor style data with images
export interface FloorStyle {
	id: string;
	name: string;
	description: string;
	imageUrl: string;
	prompt: string;
}

export const FLOOR_STYLES: FloorStyle[] = [
	{
		id: 'oak-hardwood',
		name: 'Oak Hardwood',
		description: 'Classic warm oak with natural grain',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/oakhardwood.webp',
		prompt: FLOOR_STYLE_PROMPTS['oak-hardwood'],
	},
	{
		id: 'walnut-hardwood',
		name: 'Walnut Hardwood',
		description: 'Rich dark walnut with deep tones',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/walnuthardwood.webp',
		prompt: FLOOR_STYLE_PROMPTS['walnut-hardwood'],
	},
	{
		id: 'white-marble',
		name: 'White Marble',
		description: 'Elegant white marble with grey veining',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/whitemarbel.webp',
		prompt: FLOOR_STYLE_PROMPTS['white-marble'],
	},
	{
		id: 'black-marble',
		name: 'Black Marble',
		description: 'Dramatic black marble with white veining',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/blackmarble.webp',
		prompt: FLOOR_STYLE_PROMPTS['black-marble'],
	},
	{
		id: 'grey-marble',
		name: 'Grey Marble',
		description: 'Modern grey marble with subtle veining',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/greymarble.webp',
		prompt: FLOOR_STYLE_PROMPTS['grey-marble'],
	},
	{
		id: 'herringbone-wood',
		name: 'Herringbone',
		description: 'Classic herringbone wood pattern',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/herringbone.webp',
		prompt: FLOOR_STYLE_PROMPTS['herringbone-wood'],
	},
	{
		id: 'chevron-wood',
		name: 'Chevron',
		description: 'Sophisticated chevron wood pattern',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/chevron.webp',
		prompt: FLOOR_STYLE_PROMPTS['chevron-wood'],
	},
	{
		id: 'travertine',
		name: 'Travertine',
		description: 'Warm travertine stone with natural texture',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/travertine.webp',
		prompt: FLOOR_STYLE_PROMPTS['travertine'],
	},
	{
		id: 'slate',
		name: 'Slate',
		description: 'Natural slate with rich texture',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/slate.webp',
		prompt: FLOOR_STYLE_PROMPTS['slate'],
	},
	{
		id: 'concrete-polished',
		name: 'Polished Concrete',
		description: 'Modern polished concrete finish',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/polishedconcrete.webp',
		prompt: FLOOR_STYLE_PROMPTS['concrete-polished'],
	},
	{
		id: 'terrazzo',
		name: 'Terrazzo',
		description: 'Colorful terrazzo with stone chips',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/terrazzo.webp',
		prompt: FLOOR_STYLE_PROMPTS['terrazzo'],
	},
	{
		id: 'white-oak',
		name: 'White Oak',
		description: 'Light white oak with neutral tones',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/whiteoak.webp',
		prompt: FLOOR_STYLE_PROMPTS['white-oak'],
	},
	{
		id: 'geometric-tile',
		name: 'Geometric Tile',
		description: 'Modern geometric tile pattern',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/geometrictile.webp',
		prompt: FLOOR_STYLE_PROMPTS['geometric-tile'],
	},
	{
		id: 'encaustic-tile',
		name: 'Encaustic Tile',
		description: 'Colorful patterned encaustic tiles',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/encaustictile.webp',
		prompt: FLOOR_STYLE_PROMPTS['encaustic-tile'],
	},
	{
		id: 'reclaimed-wood',
		name: 'Reclaimed Wood',
		description: 'Rustic reclaimed wood with character',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/reclaimedwood.webp',
		prompt: FLOOR_STYLE_PROMPTS['reclaimed-wood'],
	},
	{
		id: 'wide-plank-oak',
		name: 'Wide Plank Oak',
		description: 'Premium wide plank oak flooring',
		imageUrl:
			'https://leafly-app.s3.eu-west-2.amazonaws.com/wideplankoak.webp',
		prompt: FLOOR_STYLE_PROMPTS['wide-plank-oak'],
	},
];

// Helper function to get floor style prompt
export function getFloorStylePrompt(floorStyleId: string): string {
	return FLOOR_STYLE_PROMPTS[floorStyleId] || FLOOR_STYLE_PROMPTS['oak-hardwood'];
}

// Helper function to check if a floor style has a detailed prompt
export function hasFloorStylePrompt(floorStyleId: string): boolean {
	return floorStyleId in FLOOR_STYLE_PROMPTS;
}

