// Detailed prompt descriptions for each interior design style
// These descriptions help the AI generate more accurate style-specific imagery

export const STYLE_PROMPTS: Record<string, string> = {
	modern: `clean lines, minimalist furniture, neutral color palette with white, grey, and black, 
		sleek surfaces, glossy finishes, geometric shapes, open floor plan, minimal ornamentation, 
		functional design, contemporary lighting, polished metal accents, glass elements, 
		uncluttered space, geometric patterns, emphasis on horizontal and vertical lines`,

	bohemian: `eclectic mix of patterns and textures, layered textiles, vintage rugs, 
		macrame wall hangings, plants and greenery, warm earthy tones with pops of vibrant colors, 
		natural materials like rattan and wicker, floor cushions, tapestries, ethnic prints, 
		global-inspired decor, artistic wall art, cozy and lived-in feel, mixed furniture styles, 
		colorful throw pillows, hanging plants, natural wood tones`,

	'dark-academia': `rich dark wood furniture, leather armchairs, vintage bookshelves filled with books, 
		antique brass lamps, deep jewel tones like burgundy, forest green, and navy, 
		classical artwork, oil paintings in ornate frames, globe and vintage maps, 
		Persian rugs, velvet upholstery, wood paneling, scholarly atmosphere, dim warm lighting, 
		gothic architectural elements, vintage study aesthetic, intellectual ambiance, 
		traditional crown molding, heavy curtains`,

	'dark-behemian': `moody color palette with deep purples, blacks, and dark greens, 
		velvet and rich textured fabrics, dramatic wall art, mystical decor elements, 
		eclectic vintage furniture, dark patterned rugs, gothic-inspired accessories, 
		candlelight and warm ambient lighting, macrame in dark tones, dried flowers, 
		antique mirrors, layered textiles in deep hues, natural elements with dark wood, 
		mysterious and enchanting atmosphere`,

	scandinavian: `light wood floors, white walls, minimal furniture with clean lines, 
		hygge atmosphere, natural light emphasis, pale color palette with whites and light grays, 
		functional Scandinavian furniture, cozy textiles like wool throws, 
		simple pendant lighting, plants as accents, decluttered space, natural materials, 
		blonde wood tones, geometric patterns in soft colors, airy and bright feel, 
		emphasis on functionality and simplicity, muted pastel accents`,

	industrial: `exposed brick walls, concrete floors, metal fixtures and pipes, 
		edison bulb lighting, weathered wood elements, open ductwork, steel beams, 
		factory-style windows, utilitarian furniture, leather seating, metal stools, 
		neutral color palette with grays and browns, unfinished surfaces, 
		repurposed industrial items, minimalist decor, raw materials, 
		warehouse aesthetic, metal shelving units, distressed finishes`,

	traditional: `classic furniture with ornate details, rich wood tones, 
		elegant upholstered pieces, damask and floral patterns, crystal chandeliers, 
		crown molding and wainscoting, formal arrangement, symmetrical layouts, 
		antique accessories, oriental rugs, warm color palette, 
		traditional artwork in gold frames, table lamps with fabric shades, 
		luxurious draperies, timeless elegance, carved wood details, 
		balanced and cohesive design`,

	minimalist: `stark white walls, extremely minimal furniture, no clutter, 
		monochromatic color scheme, essential items only, clean surfaces, 
		hidden storage solutions, simple geometric forms, negative space emphasis, 
		functional pieces with no ornamentation, bare windows or simple blinds, 
		quality over quantity, zen-like atmosphere, natural light, 
		subtle textures, neutral tones, sleek and unadorned aesthetic`,

	rustic: `reclaimed wood furniture, natural stone elements, exposed wooden beams, 
		cozy fireplace, warm earth tones, vintage farmhouse pieces, 
		natural fiber textiles like burlap and linen, wrought iron accents, 
		distressed finishes, handcrafted items, organic shapes, 
		warm ambient lighting, nature-inspired decor, wooden floors, 
		comfortable overstuffed seating, natural materials throughout, 
		casual and inviting atmosphere`,

	contemporary: `current design trends, mix of modern and traditional elements, 
		curved furniture lines, bold accent colors, artistic lighting fixtures, 
		variety of textures, geometric patterns, neutral base with color pops, 
		innovative materials, sculptural elements, asymmetrical balance, 
		open concept layout, statement pieces, glass and metal accents, 
		sophisticated and current aesthetic, attention to architecture`,

	tropical: `natural woven furniture like rattan and bamboo, lush indoor plants, 
		palm leaf prints, bright tropical colors like turquoise and coral, 
		light and airy fabrics, bamboo blinds, wicker accents, 
		tropical leaf wallpaper or art, natural light, beach-inspired decor, 
		coastal elements, white and natural wood tones, relaxed atmosphere, 
		outdoor-indoor connection, botanical prints, casual seating`,

	'art-deco': `geometric patterns and bold symmetry, luxurious materials like marble and brass, 
		rich jewel tones like emerald and sapphire, metallic accents in gold and chrome, 
		glamorous mirrors with geometric frames, velvet upholstery, 
		stepped forms and ziggurat shapes, sunburst motifs, lacquered furniture, 
		high contrast color schemes, sophisticated and elegant, 
		angular furniture, decorative screens, stylized floral patterns, 
		opulent and dramatic aesthetic`,

	'modern-farmhouse': `shiplap walls, barn doors, rustic wood beams mixed with modern furniture, 
		white or neutral color palette, industrial metal fixtures, 
		farmhouse sink, open shelving, vintage-inspired lighting, 
		clean lines with rustic textures, comfortable upholstered furniture, 
		natural materials, wooden accents, simple window treatments, 
		fresh and updated country style, mix of old and new, 
		cozy yet refined atmosphere`,

	coastal: `light blue and white color scheme, natural textures like jute and rope, 
		driftwood accents, nautical decor elements, striped patterns, 
		weathered wood furniture, sea-inspired artwork, 
		large windows with sheer curtains, bright and airy feel, 
		coral and seashell decorations, light linens, wicker furniture, 
		relaxed beach house vibe, soft sandy neutrals, ocean-inspired palette`,

	japandi: `Japanese minimalism meets Scandinavian functionality, 
		natural wood in light and medium tones, clean lines, 
		neutral color palette with warm undertones, wabi-sabi aesthetic, 
		low-profile furniture, rice paper screens or shoji-inspired elements, 
		minimal ornamentation, natural materials, zen atmosphere, 
		quality craftsmanship, subtle textures, perfect balance, 
		clutter-free space, organic shapes, handmade ceramics, 
		harmonious and peaceful design`,

	'french-country': `distressed furniture with antique finish, soft pastel colors, 
		toile patterns, floral prints, wrought iron accents, 
		rustic wooden beams, farmhouse table, upholstered chairs, 
		vintage accessories, copper cookware, open shelving with displayed dishware, 
		romantic and charming aesthetic, natural stone elements, 
		linen fabrics, chandeliers, country elegance, warm and inviting`,

	'shabby-chic': `distressed white furniture, vintage pieces with worn finishes, 
		soft pastel colors like blush pink and mint, 
		romantic floral patterns, ruffled fabrics, 
		vintage mirrors and frames, crystal chandeliers, 
		feminine and delicate aesthetic, lace accents, 
		repurposed vintage items, chippy paint finishes, 
		comfortable overstuffed seating, roses and botanical prints, 
		cottage-style charm, soft and dreamy atmosphere`,

	transitional: `blend of traditional and contemporary styles, 
		neutral color palette with strategic color accents, 
		mix of curved and straight lines, classic furniture with modern updates, 
		timeless elegance, minimal accessories, 
		comfortable and sophisticated, quality fabrics, 
		balanced proportions, subtle patterns, 
		refined yet relaxed atmosphere, versatile design elements, 
		understated luxury, clean upholstery with traditional shapes`,

	// Garden-specific style prompts - prefixed with 'garden-'
	'garden-modern': `modern minimalist garden design with clean geometric lines and forms, 
		strategic placement of architectural plants like yuccas, agaves, and ornamental grasses, 
		straight-edged pathways made from sleek materials like poured concrete or smooth pavers, 
		geometric planting beds with stark edges and angles, 
		monochromatic color scheme featuring shades of green with gray accents, 
		water features with simple geometric forms like rectangular pools or fountains, 
		minimal plant variety with emphasis on form over color, 
		structural plants like boxwood spheres and clipped hedges, 
		modern sculptures and contemporary garden art, 
		sleek outdoor furniture with clean lines, 
		strategic lighting with modern fixtures, 
		uncluttered spaces with strong visual hierarchy, 
		emphasis on negative space and balance, modern garden aesthetic`,

	'garden-bohemian': `cloudy whimsical garden filled with eclectic mix of plants and flowers, 
		colorful wildflower meadows bursting with daisies, cosmos, zinnias, and sunflowers, 
		informal and artistic garden design with no strict boundaries, 
		mixed heights and textures creating layered informal borders, 
		rustic garden elements like reclaimed wooden barrels abandoned as planters, 
		casual meandering pathways made from gravel or bark chips, 
		bohemian garden structures like repurposed arbors draped with climbing vines, 
		vibrant color combinations with warm oranges, purples, pinks, and yellows, 
		free-flowing garden layout that feels spontaneous and artistic, 
		unconventional plant arrangements mixing vegetables with flowers, 
		vintage garden accessories and found objects scattered throughout, 
		artist retreat atmosphere with creative plant combinations, 
		wild and carefree garden aesthetic with romantic cottage feel`,

	'garden-dark-academia': `moody atmospheric garden with deep rich foliage and dramatic shadows, 
		dramatic dark green and burgundy plants like black mondo grass and dark-leaved hostas, 
		formal garden structures with gothic architectural elements and ivy-covered walls, 
		stone pathways and classical garden features like weathered statuary, 
		tall hedges creating secluded intimate garden rooms for contemplation, 
		mysterious garden atmosphere with plantings that suggest scholarly pursuits, 
		dark flowering plants featuring deep purples, burgundies, and near-black blooms, 
		ivy-covered stone walls creating sense of aged intellectual grandeur, 
		classical garden sculptures and busts placed among the plantings, 
		formal plant arrangements with structured beds filled with dark foliage, 
		heavy trailing vines and climbing plants creating shadowy corners, 
		intellectual garden aesthetic with references to classical learning and literature, 
		dim lighting filtering through dense plantings creating contemplative spaces, 
		herb gardens with ancient varieties suggesting apothecary knowledge, 
		formal clipped evergreens providing year-round structure and depth`,

	'garden-dark-behemian': `mystical dark garden with moody plants and atmospheric elements, 
		dramatic deep purple and dark green foliage creating sense of mystery, 
		eclectic mix of dark flowering plants including black roses and deep purple salvias, 
		bohemian-inspired casual layout with dramatic garden elements and unexpected features, 
		gothic garden elements like iron gates and moody plant combinations, 
		atmospheric lighting through plant shadows creating enchanting atmosphere, 
		informal paths winding through dark ornamental plants and unusual specimens, 
		mysterious and enchanting garden atmosphere with witchy vibes, 
		eccentric plant combinations mixing herbs, flowers, and dark foliage, 
		weathered sculptures and vintage garden ornaments with gothic appeal, 
		night-blooming plants emphasized for their magical evening qualities, 
		deep burgundy and purple color scheme throughout plantings, 
		lush dark groundcovers like ajuga and dead nettle creating rich carpet, 
		ornamental grasses with dark seed contributing to overall moody aesthetic, 
		artistic and unconventional dark garden design with bohemian flair`,

	'garden-scandinavian': `light and airy garden design with simplicity and functionality, 
		simple clean lines with white and light-colored flowers dominating the palette, 
		minimal plant varieties arranged harmoniously in simple blocks, 
		light birch trees and pale flowering shrubs like hydrangeas and viburnums, 
		simple geometric pathways with pale gravel or light wood decking, 
		functional garden layout with emphasis on outdoor living and dining spaces, 
		calm and peaceful atmosphere with hygge-inspired garden seating areas, 
		pale color palette featuring whites, soft pastels, and silver-gray foliage, 
		light materials like white gravel, pale wood planters, and light-colored stones, 
		uncluttered garden space with clear organization and purpose, 
		scandinavian minimalism emphasizing quality over quantity in plantings, 
		simple outdoor furniture with clean lines and natural materials, 
		low-maintenance plants suited to northern climates, 
		functional herb and vegetable gardens integrated simply, 
		air of tranquility and balance with emphasis on natural materials`,

	'garden-industrial': `urban industrial garden with metal and concrete elements throughout, 
		concrete planters and metal raised beds creating structural framework, 
		architectural plants with strong lines like palm trees, cordylines, and phormiums, 
		repurposed industrial materials as planters like old pipes and steel troughs, 
		modern urban gardening approach with emphasis on container gardening, 
		gritty and raw garden aesthetic with exposed materials and unfinished surfaces, 
		steel and concrete garden features including fountains and pathway edging, 
		bold structural plants arranged for maximum visual impact, 
		urban wildflowers adapted to tough conditions mixed with contemporary plants, 
		industrial courtyard garden feel suggesting urban loft living, 
		utilitarian garden design with emphasis on functionality and durability, 
		metal trellises and wire supports for climbing plants, 
		poured concrete seating and surfaces creating industrial vibe, 
		bright flowering plants creating contrast against gray industrial backdrop, 
		modernist planting design with strong geometric forms and urban sensibility`,

	'garden-contemporary': `current modern garden trends with innovative design approaches, 
		mix of traditional and modern garden elements creating sophisticated blend, 
		innovative garden materials and plantings showcasing latest landscape trends, 
		curved garden pathways with organic flowing lines mixed with angular features, 
		bold accent colors in plantings creating focal points and visual interest, 
		sophisticated garden layout with multiple outdoor rooms and destinations, 
		modern garden sculptures and contemporary art pieces integrated naturally, 
		contemporary plant varieties including new introductions and designer selections, 
		sleek and current garden aesthetic with emphasis on style and innovation, 
		innovative garden design elements like living walls and modern water features, 
		seating areas designed for entertaining and outdoor living, 
		mixed plant communities creating ecological interest, 
		strategic use of ornamental grasses and perennials for year-round appeal, 
		balanced combination of hardscaping and plantings creating outdoor living space, 
		timeless yet trendy garden design with contemporary appeal and lasting beauty`,

	'garden-art-deco': `geometric garden patterns and designs with art deco styling, 
		symmetrical formal layouts with bold art deco motifs and geometric shapes, 
		luxurious garden materials and features suggesting glamour and sophistication, 
		bold geometric plant arrangements with plants trimmed into angular forms, 
		rich jewel tones in flower colors including emerald greens, sapphire blues, and ruby reds, 
		glamorous garden aesthetic with emphasis on luxury and refinement, 
		stepped garden terraces and geometric pathways creating three-dimensional interest, 
		decorative geometric garden ornaments with art deco styling throughout, 
		high contrast garden color schemes with strong dark and light elements, 
		angular garden features including clipped hedges in geometric patterns, 
		stepped forms and ziggurat shapes in planters and raised beds, 
		sunburst motifs incorporated into pathway designs and plant arrangements, 
		metallic accents in garden furniture and decorative elements, 
		lush plantings with dramatic forms creating sense of luxury, 
		formal elegance with geometric precision suggesting 1920s glamour and sophistication`,

	'garden-modern-farmhouse': `rustic farmhouse garden with modern updates and contemporary touches, 
		rustic wooden elements mixed with clean modern lines creating balanced aesthetic, 
		herb and vegetable gardens integrated with flowers for both beauty and function, 
		farmhouse-inspired garden structures like raised bed kits and rustic trellises, 
		natural materials like reclaimed wood planters and stone pathways, 
		fresh and updated country garden style blending traditional and modern elements, 
		cozy yet refined garden atmosphere perfect for outdoor family gatherings, 
		mix of traditional and modern garden elements creating relaxed sophistication, 
		rustic garden pathways made from flagstones or simple gravel with wooden edging, 
		comfortable outdoor furniture with farmhouse charm and modern durability, 
		functional garden spaces for growing food alongside ornamental plantings, 
		warm earth tones with neutral palette punctuated by bright kitchen garden colors, 
		simple gothic arches and rustic garden gates adding character, 
		visually appealing garden design combining practicality with country style, 
		inviting garden atmosphere suggesting farm-to-table lifestyle and outdoor living`,

	'garden-coastal': `beach-inspired garden with coastal plants and seaside theme, 
		salt-tolerant coastal vegetation adapted to harsh marine conditions, 
		sandy pathways and driftwood elements creating beachy natural aesthetic, 
		nautical garden decor and features including weathered ropes and marine accessories, 
		sea-inspired color palette with cool blues, whites, and sandy neutrals, 
		relaxed beach house garden vibe perfect for casual entertaining, 
		soft sandy tones and ocean blues in plantings mirroring coastal colors, 
		coastal grasses like blue fescue and beach grasses creating texture, 
		light and airy coastal garden atmosphere with sense of openness, 
		relaxing seaside garden aesthetic suggesting vacation lifestyle, 
		driftwood sculptures and beachcombing treasures integrated throughout, 
		plants with silver foliage reflecting seaside conditions like artemisia and sea holly, 
		simple weathered furniture suggesting casual beach living, 
		wave-inspired curves in pathways and beds mimicking ocean motion, 
		coastal landscaping suitable for seaside gardens with maritime character`,

	'garden-french-country': `charming french country garden design with rustic elegance, 
		distressed rustic garden elements including vintage planters and tools, 
		french country flowers and herbs like lavender, sage, and rosemary, 
		romantic garden pathways and borders with informal cottage feel, 
		soft pastel colors in flowers including pale pinks, lavenders, and creamy whites, 
		romantic and charming garden aesthetic with emphasis on flowers and fragrance, 
		french country garden structures like trellises with climbing roses, 
		vintage garden accessories and antiques placed thoughtfully throughout, 
		rustic wooden garden furniture and planters with weathered patina, 
		country elegance garden feel blending sophistication with casual charm, 
		herb gardens arranged informally with flowers for cottage effect, 
		romantic roses mixed with traditional french country flowers, 
		stone paths and gravel areas creating rustic base for plantings, 
		warm earth tones with soft colors creating harmonious garden palette, 
		inviting garden atmosphere with emphasis on outdoor dining and relaxation`,

	'garden-shabby-chic': `distressed and weathered garden elements with vintage charm, 
		soft pastel flowers with white and pink blooms creating romantic palette, 
		romantic garden design with vintage feel suggesting faded elegance, 
		weathered wood planters and garden furniture with chippy white paint, 
		feminine and delicate garden plants including roses, hydrangeas, and delphiniums, 
		vintage garden accessories and ornaments suggesting flea market finds, 
		romantic roses and soft pastel flowers dominating the color scheme, 
		chippy paint finishes on garden structures creating weathered charm, 
		cottage-style garden charm with emphasis on flowers and romantic atmosphere, 
		soft and dreamy garden atmosphere suggesting lazy summer days, 
		mismatched vintage furniture creating eclectic comfortable seating areas, 
		rose-covered arbors and trellises dripping with blooms, 
		herbaceous borders with cottage garden flowers in soft colors, 
		distressed signs and vintage decorations adding whimsical character, 
		romantic garden aesthetic with emphasis on flowers, fragrance, and vintage charm`,

	'garden-transitional': `blend of traditional and contemporary garden styles with timeless appeal, 
		neutral garden palette with strategic color accents for visual interest, 
		mix of curved and straight garden pathways creating balanced flow, 
		classic garden elements with modern updates combining best of both worlds, 
		timeless garden elegance with refined yet relaxed atmosphere, 
		balanced garden proportions ensuring harmonious overall design, 
		subtle plant combinations avoiding extremes in color or form, 
		versatile garden design elements serving multiple purposes, 
		understated luxury garden feel with emphasis on quality materials, 
		clean traditional garden shapes updated with contemporary plant selections, 
		formal structure softened by more relaxed plantings, 
		foundational shrubs and trees providing year-round structure, 
		seasonal interest from carefully selected perennials and bulbs, 
		harmonious color scheme with carefully chosen accent colors, 
		transitional garden aesthetic balancing tradition with contemporary sensibility`,

	'garden-traditional': `formal traditional garden with classic design principles and timeless structure, 
		formal garden layout with symmetrical design and balanced proportions, 
		box hedges and topiary creating geometric garden rooms and defined spaces, 
		herbaceous borders with classic perennial flowers in coordinated color schemes, 
		classic roses including hybrid teas and grandifloras in formal arrangements, 
		symmetrical design with central axis and matching elements on either side, 
		immaculate lawn serving as green carpet for formal garden spaces, 
		traditional english garden with emphasis on flowers and color throughout seasons, 
		colorful perennial borders combining plants for continuous bloom, 
		fountain or water feature as centerpiece creating focal point and tranquil sound, 
		gazebo or garden structures providing destination points and architectural interest, 
		classical garden elements including urns, statuary, and formal seating, 
		manicured and structured aesthetic with emphasis on maintenance and perfection, 
		formal pathways connecting garden rooms creating sense of procession, 
		timeless elegance with emphasis on traditional gardening principles and proven designs`,

	'garden-tropical': `lush tropical garden paradise with exotic plants and vibrant colors, 
		dense tropical foliage creating jungle-like atmosphere and sense of lush abundance, 
		large banana leaves and philodendrons suggesting tropical rainforest, 
		bold and colorful blooms including hibiscus, bird of paradise, and cannas, 
		exotic and vibrant atmosphere with emphasis on dramatic tropical foliage, 
		tropical fruit trees where climate permits adding edible interest, 
		palm trees and cycads creating vertical tropical structure, 
		water features with tropical themes including lush poolside plantings, 
		jungle-like density with plants competing for space creating tropical chaos, 
		warm and humid feeling plants suited to tropical or heated greenhouse conditions, 
		bromeliads and ferns adding texture and interest in shaded areas, 
		bold leaf patterns from plants like caladiums and colocasias, 
		vibrant color combinations with hot colors like orange, magenta, and lime green, 
		tropical paradise aesthetic suggesting exotic vacation destinations, 
		lush plantings creating privacy and sense of being immersed in tropical environment`,

	'garden-japandi': `japanese-inspired garden with scandinavian simplicity creating zen harmony, 
		serene zen atmosphere with emphasis on tranquility and peaceful contemplation, 
		carefully placed rocks suggesting natural landscapes and providing focal points, 
		pruned trees and bonsai creating miniature landscapes with mature character, 
		minimalist plant arrangement with strategic placement and emphasis on individual specimens, 
		water features like koi ponds or simple fountains providing calming sounds, 
		moss-covered stones creating sense of age and natural weathering, 
		bamboo groves providing rustling sound and vertical structure, 
		stone lanterns adding traditional japanese garden elements, 
		raked gravel patterns suggesting water flow and meditation, 
		peaceful meditation space designed for quiet contemplation and mindfulness, 
		natural harmony balancing man-made elements with natural beauty, 
		emphasis on tranquility and balance creating sense of peace, 
		sparse but intentional planting ensuring every element has purpose, 
		natural materials including stone, bamboo, and weathered wood throughout`,
};

// Helper function to get style-specific prompt enhancement
export function getStylePrompt(styleId: string): string {
	return STYLE_PROMPTS[styleId] || STYLE_PROMPTS['modern'];
}

// Helper function to check if a style has a detailed prompt
export function hasStylePrompt(styleId: string): boolean {
	return styleId in STYLE_PROMPTS;
}
